version: '3'
services:

  Balancer-api:
    build: ./Balancer-api/
    networks:
      - quiznet
    ports:
      - "6000:80"
    depends_on:
      - api

  Balancer-app:
    build: ./Balancer-app/
    networks:
      - quiznet
    ports:
      - "5000:80"
    depends_on:
      - client

  api: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "6001:6000"
    environment:
      SERVER_TAG: "api_1"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "server456"
      DATABASE_OPTION_DATABASE: "todosDB"

    depends_on:
      - database
    links:
     - "database"


  api-2: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "6002:6000"
    environment:
      SERVER_TAG: "api_2"
      DATABASE_SERVER: "BDSQLserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "server456"
      DATABASE_OPTION_DATABASE: "todosDB"

    depends_on:
      - database
    links:
     - "database"

  primercliente:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:6000/api/todos"
    networks:
      - quiznet
    ports:
      - "5001:80"
    depends_on:
      - basedatos

  segundocliente:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:6000/api/todos"
    networks:
      - quiznet
    ports:
      - "5002:80"
    depends_on:
      - basedatos

  basedatos:
    image: "mcr.microsoft.com/mssql/server"
    hostname: "BDSQLserver"
    networks:
      - quiznet
    volumes:
      - quizdata:/var/opt/mssql/
    environment:
      SA_PASSWORD: "server456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"


networks:
  quiznet:
    driver: bridge

volumes:
  quizdata:
